export enum Status {
  NEW = "NEW",
  PROCESSING = "PROCESSING",
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
  DESIGNING = "DESIGNING",
  AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION",
  COMPLETED = "COMPLETED",
  EXECUTING = "EXECUTING",
  IN_ACTION = "IN_ACTION",
  DISCONTINUED = "DISCONTINUED",
  CANCELED = "CANCELED",
}
